@baseUrl = http://127.0.0.1:8080/api/

# open links in browser
http://127.0.0.1:8080/l/abc123
http://127.0.0.1:8080/l/xyz789

###
POST {{baseUrl}}li HTTP/1.1
Content-Type: application/json

{
  "original_url": "https://example.com"
}

###
GET {{baseUrl}}li/get/77811303-ef47-484b-aa04-e08b3dd154e9 HTTP/1.1

###
GET {{baseUrl}}li/getpaged?page_number=0&page_size=3 HTTP/1.1