@baseUrl = http://127.0.0.1:8080/api/

POST {{baseUrl}}li HTTP/1.1
Content-Type: application/json

{
  "original_url": "https://example.com",
  "short_url": "exmpl"
}


###

GET {{baseUrl}}li/get?id=54ec6516-2752-439f-a9ab-8345fae78283 HTTP/1.1

###

GET {{baseUrl}}li/getpaged?page_number=0&page_size=3 HTTP/1.1